Feature/aoaf 503 welsh for page
companieshouse/presenter-account-web pull request #143
Opened 2024-10-02 15:13 UTC by wdhda-ch

2024-10-02 15:18 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-10-03 08:21 UTC, ch-skathirvel approved these changes

2024-10-04 07:32 UTC, ch-code-analysis commented
CI: No security warnings found

2024-10-04 08:33 UTC, ch-skathirvel requested changes

2024-10-04 08:33 UTC, ch-skathirvel commented on src/routers/handlers/confirm_company/index.ts
> +        return url + "?" + QueryParameters.COMPANY_NUMBER + "=" + companyNumber;
Instead concat with +, can we use like below?
return `${url}?${QueryParameters.COMPANY_NUMBER}=companyNumber`;

2024-10-04 08:48 UTC, ch-skathirvel approved these changes

2024-10-04 08:48 UTC, merged

2024-10-04 08:49 UTC, ch-code-analysis commented
CI: No security warnings found